### ISSUE TITLE
dd commands on wiki seem unnecessary and misleading

### ISSUE THREAD

**Issue by v1993** [nitanmarcel/isodrive#3]
A few tutorials on wiki suggest to use `dd` for converting supposedly "raw" image to ISO format. However, the only thing listed `dd` invocations do is perform a bit-perfect copy – which means that they are functionally the same as simply changing file extension, except slower.

This also leads to another question - if there's no conversion being performed, why are those files referred to as ISO, anyways? In case of image exported from qemu, for example, it will maintain whatever partition table/file system(s) it had, not become ISO.

**Comment by nitanmarcel** [comment]
The wiki should be read-write for everyone so it can always be updated by contribuitors if needed.

I just found a random tutorial online I used it as a reference for that wiki page.
