### ISSUE TITLE
persistence using isodrive 

### ISSUE THREAD

**Issue by Akash23q2** [nitanmarcel/isodrive#6]
How to get persistence working on supported linux distros using isodrive .

**Comment by nitanmarcel** [comment]
> How to get persistence working on supported linux distros using isodrive .

What do you mean by persistence

**Comment by Akash23q2** [comment]
> > How to get persistence working on supported linux distros using isodrive .
> 
> What do you mean by persistence

Where the system files are preserved across boots, unlike live usb where you lose data after reboot , certain linux distros support making a persistent usb so that you can use it without data loss. Like Ubuntu , Linux mint, mxlinux etc.

I found this
https://www.reddit.com/r/linuxmasterrace/comments/16ewg4b/using_my_phone_to_host_persistent_mx_linux_iso/

**Comment by nitanmarcel** [comment]
> > > How to get persistence working on supported linux distros using isodrive .
> > 
> > 
> > What do you mean by persistence
> 
> Where the system files are preserved across boots, unlike live usb where you lose data after reboot , certain linux distros support making a persistent usb so that you can use it without data loss. Like Ubuntu , Linux mint, mxlinux etc.
> 
> I found this https://www.reddit.com/r/linuxmasterrace/comments/16ewg4b/using_my_phone_to_host_persistent_mx_linux_iso/

With the `-rw` flag you can set the read write mode. You might need to install the OS with KVM and create a bootable environment from it for isodrive

https://github.com/nitanmarcel/isodrive/wiki/Convert-an-OS-into-a-bootable-environment
